### ISSUE TITLE
Paths to unrar/7z not found

### ISSUE THREAD

**Issue by epogrebnyak** [Nikola-K/flask_cbr#1]
Command ```unpack 101 2015-06``` is not executed because paths to unrar/7z not found. 

```
Date: 2015-06-01
File: 101-20150601.rar

Calling:
"/home/flask_cbr/flask_cbr/cbr-db/bin/unrar.exe" e /home/flask_cbr/flask_cbr/cbr-db/data.downloadable/101/rarzip/101-20150601.rar /home/flask_cbr/flask_cbr/cbr-db/data.downloadable/101/dbf -y 
Elapsed time: 0.0
/bin/sh: 1: /home/flask_cbr/flask_cbr/cbr-db/bin/unrar.exe: not found
```

**Comment by epogrebnyak** [comment]
/home/flask_cbr/flask_cbr/cbr-db/bin/unrar.exe should it be /home/flask_cbr/cbr-db/bin/unrar.exe? 

In https://github.com/epogrebnyak/cbr-db/blob/master/py3/global_ini.py:

DIR_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# points to root folder of 'cbr-db' repo

PATH = {'unrar': os.path.join(DIR_ROOT, 'bin', 'unrar.exe'),
           'z7': os.path.join(DIR_ROOT, 'bin', '7za')}

**Comment by Nikola-K** [comment]
In `global_ini.py` https://github.com/epogrebnyak/cbr-db/blob/master/py3/global_ini.py#L15 The locations of the files are hard coded, to fix the issue it should be set to the OS paths, on linux that would be:

    PATH = {'unrar': 'usr/bin/unrar'),
                   'z7': 'usr/bin/7z}

Those packages may not be installed by default and can be installed by running `$ apt install 7zip unrar`. And their location can be found by running `$ which unrar` and `$ which 7zip`

Note I'm not totally sure if it's `7z` or `7zip` on Linux, so try both of those and see which one works.

**Comment by epogrebnyak** [comment]
Is it a good idea to add ```$ apt install 7zip unrar``` as a part of https://github.com/Nikola-K/flask_cbr/blob/master/fabfile.py, maybe as a separate fucntion (not to-do, just advice)

**Comment by Nikola-K** [comment]
7zip and unrar are cbr-db dependencies, I'm not sure if having the flask frontend install them would be the best choice. The dependencies for the `cbr-db` project should be handled separately from this script.

However adding that is easy if someone wants to do it that way.
