### ISSUE TITLE
Need MySQL web interface to work with dbf_db and cbr_db

### ISSUE THREAD

**Issue by epogrebnyak** [Nikola-K/flask_cbr#5]
E.g phpMyAdmin (?) or Adminer (?)

**Comment by Nikola-K** [comment]
Out of the scope for this project.

But no, you do not need those interfaces to configure cbr-db. You can just use the `$ mysql` command in terminal.

If you like GUI tools more then installing phpmyadmin or something similar can be done.

**Comment by epogrebnyak** [comment]
These are follow-up things, you do not have to fix them now, wait for
pipeline to build and let's discuss how to proceed.
9 июля 2015 г. 13:20 пользователь "Nikola Kovacevic" <
notifications@github.com> написал:
