### ISSUE TITLE
"Connection refused" on all links from homepage. 

### ISSUE THREAD

**Issue by epogrebnyak** [Nikola-K/flask_cbr#7]
I get following error on click to [Download](http://46.101.245.169:5000/downloads) and on supplying password. I rebooted server, but error persists.

```
Network Error (tcp_error) 

A communication error occurred: "Connection refused"
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.

For assistance, contact your network support team.
```

**Comment by Nikola-K** [comment]
If you can login to your server try running `supervisorctl start flask_cbr` to restart the script. But nginx should be running on startup...

**Comment by epogrebnyak** [comment]
```supervisorctl start flask_cbr``` says 'ERROR: already strated'

**Comment by Nikola-K** [comment]
It looks like nginx isn't running, or some other network issue. You might wanna look into that. Try restarting nginx or just running the `fab create` command which should also do it.

**Comment by epogrebnyak** [comment]
Did you do anything on a server? It is back to work.

**Comment by Nikola-K** [comment]
No I didn't do anything
